GymApp/Controllers/MembershipTypeController.cs
using GymApp.Data;
using Microsoft.AspNetCore.Mvc;
using GymApp.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Controllers
{
    public class MembershipTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        string duration;
        string searchPhrase;
        public MembershipTypeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MembershipTypeModel> objMembershipsList = _db.MembershipTypes;
            ViewBag.Duration = this.duration;
            ViewBag.SearchPhrase = this.searchPhrase;
            return View(objMembershipsList);
        }
        
        public async Task<IActionResult> ShowSearchResult(String SearchPhrase, String durationFilter)
        {
            var membershipTypes=  _db.MembershipTypes;
            if (!(string.IsNullOrEmpty(SearchPhrase)) && !(string.IsNullOrEmpty(durationFilter)))
            {

                this.searchPhrase = SearchPhrase;
                this.duration = durationFilter;

                if (durationFilter.Equals("All"))
                {
                    return View("Index", await membershipTypes.Where(j => j.Name.Contains(SearchPhrase)).ToListAsync());

                }
                return View("Index", await membershipTypes.Where(mmtype=>mmtype.Name.Contains(SearchPhrase) && mmtype.Duration.Contains(durationFilter)).ToListAsync());

            }
            else if (!(string.IsNullOrEmpty(SearchPhrase)))
            {
                this.searchPhrase = SearchPhrase;

                return View("Index", await membershipTypes.Where(j => j.Name.Contains(SearchPhrase)).ToListAsync());

            }else if (!(string.IsNullOrEmpty(durationFilter)))
            {
                this.duration = durationFilter;

                if (durationFilter.Equals("All"))
                {
                    return View("Index", await membershipTypes.ToListAsync());
                }
                return View("Index", await membershipTypes.Where(j => j.Duration.Contains(durationFilter)).ToListAsync());

            }

            return View("Index", await membershipTypes.ToListAsync());
        }

    }
}

GymApp/Views/Shared/LoginCustom.cshtml
@inject SignInManager<IdentityUser> signInManager;

<ul class="navbar-nav ml-auto">
    @if (signInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <form method="post" asp-controller="Account" asp-action="logout"><!--User method post instead of get to avoid malicious users from setting url links to logout the user-->
                <button type="submit" class="nav-link btn btn-link py-0 text-light" style="width:auto;">
                    Logout @User.Identity.Name
                </button>
            </form>
        </li>
    }else{
    <li class="nav-item">
        <a class="nav-link text-light" asp-controller="Account" asp-action="Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-light" asp-controller="Account" asp-action="Login">Login</a>
    </li>
    }
</ul>

GymApp/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GymApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" />
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body style="background-color:#555">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3 bg-gradient">
            <div class="container">
                <a class="navbar-brand text-light mr-3" asp-area="" asp-controller="Home" asp-action="Index"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-globe mr-1" viewBox="0 0 16 16">
  <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855A7.97 7.97 0 0 0 5.145 4H7.5V1.077zM4.09 4a9.267 9.267 0 0 1 .64-1.539 6.7 6.7 0 0 1 .597-.933A7.025 7.025 0 0 0 2.255 4H4.09zm-.582 3.5c.03-.877.138-1.718.312-2.5H1.674a6.958 6.958 0 0 0-.656 2.5h2.49zM4.847 5a12.5 12.5 0 0 0-.338 2.5H7.5V5H4.847zM8.5 5v2.5h2.99a12.495 12.495 0 0 0-.337-2.5H8.5zM4.51 8.5a12.5 12.5 0 0 0 .337 2.5H7.5V8.5H4.51zm3.99 0V11h2.653c.187-.765.306-1.608.338-2.5H8.5zM5.145 12c.138.386.295.744.468 1.068.552 1.035 1.218 1.65 1.887 1.855V12H5.145zm.182 2.472a6.696 6.696 0 0 1-.597-.933A9.268 9.268 0 0 1 4.09 12H2.255a7.024 7.024 0 0 0 3.072 2.472zM3.82 11a13.652 13.652 0 0 1-.312-2.5h-2.49c.062.89.291 1.733.656 2.5H3.82zm6.853 3.472A7.024 7.024 0 0 0 13.745 12H11.91a9.27 9.27 0 0 1-.64 1.539 6.688 6.688 0 0 1-.597.933zM8.5 12v2.923c.67-.204 1.335-.82 1.887-1.855.173-.324.33-.682.468-1.068H8.5zm3.68-1h2.146c.365-.767.594-1.61.656-2.5h-2.49a13.65 13.65 0 0 1-.312 2.5zm2.802-3.5a6.959 6.959 0 0 0-.656-2.5H12.18c.174.782.282 1.623.312 2.5h2.49zM11.27 2.461c.247.464.462.98.64 1.539h1.835a7.024 7.024 0 0 0-3.072-2.472c.218.284.418.598.597.933zM10.855 4a7.966 7.966 0 0 0-.468-1.068C9.835 1.897 9.17 1.282 8.5 1.077V4h2.355z"/>
</svg>Planet Fitness</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                   <!-- <partial name="_LoginPartial"/>-->
                    <partial name="LoginCustom" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="MembershipType" asp-action="Index">Membership offers</a>
                        </li>
                        @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Administration" asp-action="ListRoles">Manage Roles</a>
                            </li>
                        }
                    </ul>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 text-light ">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-light bg-primary bg-gradient bg-opacity-75" style="position:absolute;width: 100%;white-space: nowrap;line-height: 60px;top:100%;">
        <div class="container">
            <div class="row">
            <p class="col">
            &copy; 2022 - GymApp
            </p>
            <!--<a asp-controller="Admin" asp-action="Login" class="col text-light" style="text-decoration:none;">Admin Login</a>-->
            </div>
        </div>
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <!--Those two previous scripts rely on jquery and provide instant client-side validation instead of relying on server side validation
    -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

GymApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <style>
        .toast-success {
          background-color: #00ff00;
        }
        .toast-message a,
        .toast-message label {
          color: #000000;
        }
        .toast-message a:hover {
          color: #555;
          text-decoration: none;
        }
    </style>
    <script type="text/javascript">
        toastr.options = {
          "closeButton": false,
          "debug": false,
          "newestOnTop": true,
          "progressBar": false,
          "positionClass": "toast-bottom-center",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
        toastr.success('@TempData["success"]');
        
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <style>
        .toast-error {
          background-color: #ff0000;
        }
        .toast-message a,
        .toast-message label {
          color: #000000;
        }
        .toast-message a:hover {
          color: #555;
          text-decoration: none;
        }
    </style>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}